spring.application.name=futreserve-backend

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://estebann8312:1234@cluster0.dkg0m.mongodb.net/futreserve?retryWrites=true&w=majority&appName=Cluster0

# JWT
jwt.secret=futreserve-super-secret-jwt-key-for-hs256-algorithm-must-be-256bits
jwt.expiration=86400000

# Server
server.port=8080
